application: appengine-try-php
version: 1
runtime: php
api_version: 1

handlers:
- url: /.*
  script: public/index.php

env_variables:
 DEVELOPMENT_DB_HOST: '127.0.0.1:3306'
 DEVELOPMENT_DB_USERNAME: 'root'
 DEVELOPMENT_DB_PASSWORD: 'Chenlx201125'
 DEVELOPMENT_DB_NAME: 'phpdb'
 PRODUCTION_CLOUD_SQL_INSTANCE: ''
 PRODUCTION_DB_USERNAME: ''
 PRODUCTION_DB_PASSWORD: ''
 PRODUCTION_DB_NAME: 'TK_Test'
